// <auto-generated />
using System;
using Frinfo.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Frinfo.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200223173331_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Frinfo.Shared.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Fridge");

                    b.HasData(
                        new
                        {
                            FridgeId = 1,
                            HouseholdId = 1,
                            Name = "Kitchen"
                        },
                        new
                        {
                            FridgeId = 2,
                            HouseholdId = 1,
                            Name = "Cellar"
                        });
                });

            modelBuilder.Entity("Frinfo.Shared.FridgeItem", b =>
                {
                    b.Property<int>("FridgeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ItemImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeItemId");

                    b.HasIndex("FridgeId");

                    b.ToTable("FridgeItem");

                    b.HasData(
                        new
                        {
                            FridgeItemId = 1,
                            ExpirationDate = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FridgeId = 2,
                            Name = "French Fries"
                        },
                        new
                        {
                            FridgeItemId = 2,
                            FridgeId = 2,
                            Name = "Chicken Nuggets"
                        },
                        new
                        {
                            FridgeItemId = 3,
                            ExpirationDate = new DateTime(2020, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FridgeId = 1,
                            Name = "Salmon"
                        },
                        new
                        {
                            FridgeItemId = 4,
                            FridgeId = 1,
                            Name = "Ice Cream"
                        });
                });

            modelBuilder.Entity("Frinfo.Shared.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HouseholdCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseholdId");

                    b.ToTable("Households");

                    b.HasData(
                        new
                        {
                            HouseholdId = 1,
                            HouseholdCode = "1337",
                            Name = "Test Household"
                        });
                });

            modelBuilder.Entity("Frinfo.Shared.Fridge", b =>
                {
                    b.HasOne("Frinfo.Shared.Household", "Household")
                        .WithMany("Fridges")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frinfo.Shared.FridgeItem", b =>
                {
                    b.HasOne("Frinfo.Shared.Fridge", "Fridge")
                        .WithMany("Items")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
